# Generated by Django 5.0.4 on 2024-04-11 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bugreport',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='bugreport',
            old_name='updated_ad',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='featurerequest',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='featurerequest',
            old_name='updated_ad',
            new_name='updated_at',
        ),
    ]
