# Generated by Django 5.0.4 on 2024-04-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_control', '0003_bugreport_status_alter_bugreport_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Ниже среднего'), (3, 'Средний'), (4, 'Выше среднего'), (5, 'Высокий')]),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Низкий'), (2, 'Ниже среднего'), (3, 'Средний'), (4, 'Выше среднего'), (5, 'Высокий')]),
        ),
    ]
